export const BLOCK_UNIQUE_CLASS_NAME = `order-block-custom-block`;
export const PRODUCT_BLOCK_EMPTY_CLASS = 'order-block-custom-block-empty';
export const ATTR_NAME_RECOMMENDATION_GROUPS = 'order-block-data-custom-groups';
export const ATTR_NAME_BLOCK_CONFIGURATION = `order-block-esd-dev-custom-config`;
export const CONTROL_NAME_PREFIX = `order-block`;
export const CONTROL_NAME_BLOCK_GROUPS = `${CONTROL_NAME_PREFIX}_blockGroups_control`;
export const CONTROL_NAME_BLOCK_TEXT = `${CONTROL_NAME_PREFIX}_blockText_control`;
export const ORIENTATION_HORIZONTAL = 'horizontal';
export const ORIENTATION_VERTICAL = 'vertical';
export const EVENT_NAME_LAYOUT_CHANGED = 'layoutChanged';
export const BLOCK_TYPE = 'Orders';
export const EMAILRENDER_APIPATH = 'api/v1.0/contentblocks';
export const EMAILRENDER_TEMPLATE_APIPATH = 'api/v1.0/templates';
export const ALERT_MESSAGE_BLOCK_NOT_LOADED = 'alertMessage.content.block.notloaded';
export const BLOCK_NAME = 'display.blockName';
export const BLOCK_CONTENT_ERROR = 'alertMessage.content.block.error';
export const BLOCK_CONTENT_NO_HTML = 'alertMessage.content.block.nohtml';
export const PREVIEW_EMPTY_DESCRIPTION = 'preview.empty.description';
export const PREVIEW_LABEL = 'preview.label';
export const TARGET_DROPDOWN = 'js-target-dropdown';
export const SELECT_FIELD = 'js-select-field';
export const BLOCK_TYPE_SHOW = 'block-type-show';
export const BLOCK_CONTENT_HIGHLIGHT = 'block-type-content-highlight';
export const ALERT_MODAL = 'alert-modal';
export const CLOSE_ALERT_MODAL = 'closeAlertModal';
export const CLOSE_ALERT_MODAL_FUNCTION = 'closeAlertModal();';
export const CUSTOM_BLOCK_TEXT = 'custom-block-text';
export const BLOCK_DESIGN_ENDPOINT='contentblocks';
export const CONTENT_TYPE_URLENCODED = 'application/x-www-form-urlencoded; charset=UTF-8';
export const CONTENT_TYPE = 'application/json; charset=UTF-8';

